### ISSUE TITLE
how to save the prompt-tuned models and config.json files?

### ISSUE THREAD

**Issue by dqxiu** [thunlp/OpenPrompt#1]
Hi! Thanks for your job and I've run some experimental experiments smoothly. However, I wonder if it is possible to save the prompt-tuned models and config.json files via writing a path to the config.yaml file?

**Comment by ningding97** [comment]
Hi, thanks for your attention! We are still developing and debugging this feature and it will be online soon.

**Comment by ningding97** [comment]
> Hi! Thanks for your job and I've run some experimental experiments smoothly. However, I wonder if it is possible to save the prompt-tuned models and config.json files via writing a path to the config.yaml file?

Hi, thanks for your attention! We are still developing and debugging this feature and it will be online soon.

**Comment by ShengdingHu** [comment]
This feature has been added. Now the checkpoints, together with the logs, will be saved in the logging directory which is automatically made. Thanks for your comment!
