### ISSUE TITLE
    from typing import OrderedDict ImportError: cannot import name 'OrderedDict'

### ISSUE THREAD

**Issue by KX-Lau** [thunlp/OpenPrompt#10]
I found a bug while using the project OpenPrompt.
When the python version is less than 3.7, an error will be reported when using  from typing import OrderedDict, which should be modified to from collections import OrderedDict
When the python version is equal to or higher than 3.7, from typing import OrderedDict will work normally
I think different import statements should be used depending on the python version.
Hope to adopt!

**Comment by ningding97** [comment]
Thanks, we will apply and adapt OpenPrompt to different environments!
