### ISSUE TITLE
How to replicate text classification experiments e.g. agnews

### ISSUE THREAD

**Issue by NtaylorOX** [thunlp/OpenPrompt#100]
Amazing work! Apologies if this is a newbie question, but I am quite new to working with such repos and whilst can get the tutorials to run smoothly. I wonder if there is advice to running one of the text classifications task e.g. agnews using the ./experiments/classification_mixed_prompt.yaml file?

Any help would be much appreciated

**Comment by ShengdingHu** [comment]
yaml files are used for systematic experiments. To get some insight of how to use openprompt, please refer to tutorial/ e.g.
```
python tutorial/0_basic.py
```
If you have any further questions, please let us know:)

**Comment by NtaylorOX** [comment]
Thank you for the reply. I have become quite familiar with the tutorial scripts, it was more directly how to replicate experiments using the yaml files to set the relevant parameters etc. Unless there is any further advice, feel free to close the issue 👍
