### ISSUE TITLE
Shape mismatch in auto_v - tutorial/ 3.1_LMBFF.py

### ISSUE THREAD

**Issue by NtaylorOX** [thunlp/OpenPrompt#101]
When running this tutorial script as is, a shape mismatch appears when trying to auto generate the verbaliser. The code run is as it is on github. Error output below. Without knowing the fine details of the auto verbalizer, its hard to deduce where exactly this is going wrong. Any thoughs?

load model...
[[{'text': 'nothing happens , and it happens to flat characters .', 'loss_ids': 0, 'shortenable_ids': 1}, {'text': '<extra_id_0>', 'loss_ids': 1, 'shortenable_ids': 0}, {'text': ' terrible', 'loss_ids': 0, 'shortenable_ids': 0}, {'text': '<extra_id_1>', 'loss_ids': 1, 'shortenable_ids': 0}, {'text': '.', 'loss_ids': 0, 'shortenable_ids': 0}], {'guid': 'train-0', 'label': 0}]
performing auto_v...
tokenizing: 32it [00:00, 798.56it/s]
Traceback (most recent call last):
  File "tutorial/3.1_LMBFF.py", line 186, in <module>
    label_words_list = verbalizer_generator.generate()
  File "/home/niallt/venvs/nlp_prompts/lib/python3.6/site-packages/openprompt/prompts/prompt_generator.py", line 447, in generate
    self.label_words_ids = self._find_verbalizer()
  File "/home/niallt/venvs/nlp_prompts/lib/python3.6/site-packages/openprompt/prompts/prompt_generator.py", line 392, in _find_verbalizer
    label_words =  self._get_top_words()
  File "/home/niallt/venvs/nlp_prompts/lib/python3.6/site-packages/openprompt/prompts/prompt_generator.py", line 414, in _get_top_words
    scores = self.probs_buffer[self.labels_buffer==label_id].mean(axis=0).cpu().numpy()
IndexError: The shape of the mask [32] at index 0 does not match the shape of the indexed tensor [448, 50265] at index 0

**Comment by cyl628** [comment]
Hi, I run the tutorial script and did not meet the issue. Maybe you are not running the latest version, try `git pull` to update.

**Comment by ziminghunmphrey** [comment]
hi @cyl628 , I meet a problem in LMBFF.py, it told CUDA out of memory. but I sent my GPU memory is enough

**Comment by NtaylorOX** [comment]
@ziminghunmphrey. This is a bit vague as you have not posted any information really. But GPU memory issues are likely tied to the batch size. Try reducing the batch_size and it will likely solve the problem
