### ISSUE TITLE
scalable code for: batch to device

### ISSUE THREAD

**Issue by wj-Mcat** [thunlp/OpenPrompt#102]
## Description

When I run the development code in my local pc(with no gpu), it will always throw the error when mapping tensor to gpu with the following code:

[code block](https://github.com/thunlp/OpenPrompt/blob/main/openprompt/trainer.py#L264)
```python
batch = batch.to("cuda:{}".format(self.config.environment.local_rank)).to_dict()
```

It should not throw the error when running on my local pc. How do you think about?

## Suggestion

After reviewing the code, it seems that you don't support parallel running in multi-machine. It only support single-machine-multi-gpu mode. Am I right? If so, I think the code should change to:

```python
batch = batch.to(self.model.device).to_dict()
```

It's more scalable. Or, I can contribute more code about device code refer to [Allennlp](https://github.com/allenai/allennlp).

**Comment by ShengdingHu** [comment]
Thanks for the suggestion, we will look into it as soon as possible.
