### ISSUE TITLE
multimodal 

### ISSUE THREAD

**Issue by Aatrox00** [thunlp/OpenPrompt#108]
InputExample is designed for single text or text pairs. Can openprompt be used in multimodal scenarioes such Visual Qestion Answering somehow?

**Comment by ShengdingHu** [comment]
Please wait for our future improvement, thanks!

**Comment by Aatrox00** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
