### ISSUE TITLE
weird template in the example

### ISSUE THREAD

**Issue by yananchen1989** [thunlp/OpenPrompt#110]
Hi guys,

I find that in this example of tutorial, the dataset is webnlg_2017, which is a text2text generation;
but line 47 shows that the template in this case is for NLI sentence pair classification.

In addition, is 2.1 a duplicate of 2.2 ?
Thanks.
https://github.com/thunlp/OpenPrompt/blob/main/tutorial/2.1_conditional_generation.py

**Comment by ShengdingHu** [comment]
Sorry about the late response, the original 2.1 script is not well-written, so we deleted it in the new version.
