### ISSUE TITLE
mix_template 如何引入多个可变的text来初始化？

### ISSUE THREAD

**Issue by dongguanting** [thunlp/OpenPrompt#112]
感谢您非常便捷的prompt 框架
![image](https://user-images.githubusercontent.com/60767110/151653611-1b528e93-36ed-4ac1-97d0-536b46a39d8e.png)
请问如果我除了text_a与text_b之外，还想引入新的可变的参数text_c到template中，该如何操作呢？

**Comment by HarrywillDr** [comment]
same question

**Comment by ShengdingHu** [comment]
Sorry for the late response, you can use "meta".
```
{"meta":"text_c"} Is it correct? {"mask"}.
```
Then you can add a example.meta["text_c"] = "some text" to your data example.
