### ISSUE TITLE
如何在T5中引入sentinel tokens？

### ISSUE THREAD

**Issue by kk19990709** [thunlp/OpenPrompt#113]
T5的预训练任务中使用了sentinel tokens，[论文](https://arxiv.org/pdf/1910.10683v3.pdf)第13页使用了`<X><Y><Z>`进行表示。
我认为，这对于提示学习是非常重要的。
可是我不知道如何在Template中添加sentinel tokens，请问OpenPrompt有没有提供相应的接口呢？

**Comment by thinksoso** [comment]
T5Tokenizer 实现了 sentinel tokens
可以参考
https://github.com/princeton-nlp/LM-BFF/blob/1bbdc42455502a152541c48974cdc71027569a2e/tools/generate_template.py#L16
