### ISSUE TITLE
Investigating trained soft template and verbalizers

### ISSUE THREAD

**Issue by NtaylorOX** [thunlp/OpenPrompt#115]
Is there any guidance on how to investigate the soft template embeddings after training? For instance, with the aim of deriving which tokens they represent by comparing with the most similar token embeddings of the PLM? 

Apologies if this is a bit vague

**Comment by ShengdingHu** [comment]
Sorry, currently we don't have a plan for adding this functionality. But you can retrieve the soft token embedding by yourself easily.
