### ISSUE TITLE
How to use DataParallel on a PromptModel?

### ISSUE THREAD

**Issue by shuaihuaiyi** [thunlp/OpenPrompt#120]
I've tried wrap `PromptModel` with `torch.nn.DataParallel` but not working. It seems somehow the type of `input_ids` in class `InputFeatures` becomes `tuple` rather than `Tensor`. Any idea to fix this?

**Comment by ShengdingHu** [comment]
I  think you should wrap the PLM into DataParallel first before passing the PLM into Prompt Model.
