### ISSUE TITLE
some problems using tutorial 5.1(Chinese dataset classification task)

### ISSUE THREAD

**Issue by 652994331** [thunlp/OpenPrompt#122]
Hi, i was trying to use tutorial 5.1 for a Chinese task, i downloaded the chn dataset and slightly modified the data_loader part and it loaded successfully. however, i got some problems like below(i also print one example loaded for sample), can you help plz? thank you.
<img width="564" alt="Screen Shot 2022-02-25 at 4 31 30 PM" src="https://user-images.githubusercontent.com/51428350/155820719-64beaf0c-0c04-44e7-adaf-5aac7aeaae6b.png">

**Comment by ShengdingHu** [comment]
It seems that your template has some problems. Could you give more information?
