### ISSUE TITLE
When input has two parts

### ISSUE THREAD

**Issue by guoxuxu** [thunlp/OpenPrompt#127]
Hi, Thanks for developing this framework. I saw the comment here [T5TokenizerWrapper](https://github.com/thunlp/OpenPrompt/blob/main/openprompt/plms/seq2seq.py#L46) says "does not consider the situation that input has two parts". For sentence pairs, does T5 need token_type_ids? In [T5Tokenizer](https://huggingface.co/docs/transformers/model_doc/t5), the documentation says it doesn't. If so, then maybe no need to differentiate inputs that have two parts?

**Comment by ShengdingHu** [comment]
Yes, T5 doesn't accept token_type_ids as the input. There is no need to differentiate inputs that have two parts actually.
