### ISSUE TITLE
 How to support multi-template when use PromptForClassification

### ISSUE THREAD

**Issue by cwlseu** [thunlp/OpenPrompt#129]
I have two template text,  as following:
```python
template_text = [
'{"placeholder":"text_b"} 是 {"placeholder":"text_a"} 的简写吗? {"mask"}',
'{"placeholder":"text_a"} 的简写 {"mask"} {"placeholder":"text_b"} .']
mytemplate = ManualTemplate(tokenizer=tokenizer, text=template_text)
```
How to support more than one template text in one `Template`.
The ManualTemplate is:
![image](https://user-images.githubusercontent.com/5145788/160096892-b39b3769-a7dd-426c-81b0-fc841c5e5115.png)

**Comment by ShengdingHu** [comment]
We don't support multi-template ensembling, since it can be easily implemented by using two templates and two prompt models. Moreover, the way of ensembling can vary greatly, according to user needs. So we leave it to the user side.

**Comment by lihuiliullh** [comment]
If I use two prompt models, how to guarantee they use the same PLM?  Is it possible to parallel train these two prompt models? @ShengdingHu
