### ISSUE TITLE
Is there anything ignored in SoftVerbalizer

### ISSUE THREAD

**Issue by wj-Mcat** [thunlp/OpenPrompt#131]
After read the source code of [soft_verbalzier](https://github.com/thunlp/OpenPrompt/blob/main/openprompt/prompts/soft_verbalizer.py), I find that the docstirng of [`process_hiddens`](https://github.com/thunlp/OpenPrompt/blob/main/openprompt/prompts/soft_verbalizer.py#L177) method describe: **which contains four steps**, but the body of method don't exit any ***steps*** code. So, I wounder that if there is anything ignored in this method ?

**Comment by ShengdingHu** [comment]
Probability errors in the docs.
