### ISSUE TITLE
'KnowledgeableVerbalizer' object has no attribute 'max_token_split'

### ISSUE THREAD

**Issue by shan23chen** [thunlp/OpenPrompt#133]
will be helpful if you can kindly include a KnowledgeableVerbalizer example and a PTRVerbalizer example!

Thanks!

**Comment by ningding97** [comment]
> will be helpful if you can kindly include a KnowledgeableVerbalizer example and a PTRVerbalizer example!
> 
> Thanks!

Thanks, we will add the corresponding examples.
