### ISSUE TITLE
Does this support prompt tuning?

### ISSUE THREAD

**Issue by ArEnSc** [thunlp/OpenPrompt#135]
Hey it sorta seems like it supports prompt tuning but how do you save the prefixes?

**Comment by ningding97** [comment]
> Hey it sorta seems like it supports prompt tuning but how do you save the prefixes?

Yes, please refer to this [link](https://github.com/thunlp/OpenPrompt/blob/main/tutorial/1.4_soft_template.py), i.e., soft prompt + freeze model = prompt tuning.

**Comment by shaoyuyoung** [comment]
Hi, I want to know if I just use soft prompt, is this also prompt tuning?

**Comment by ArEnSc** [comment]
> Hi, I want to know if I just use soft prompt, is this also prompt tuning?

prompt tuning is the category of research, soft prompting is a specific implementation of that afaik
