### ISSUE TITLE
no attribute 'tokenize_one_example'

### ISSUE THREAD

**Issue by khairunnisaor** [thunlp/OpenPrompt#138]
Hi,

thank you for your amazing work to ease the users of prompt learning.

I tried to implement the LMBFF tutorial and happened to meet this error:
```
Traceback (most recent call last):
  File "run_lmbff.py", line 116, in <module>
    dataloader = PromptDataLoader(dataset['train'], template, template_generate_tokenizer, template_tokenizer_wrapper, batch_size=len(dataset['train']), decoder_max_length=128) # register all data at once
  File "/home/oryza/playground/OpenPrompt/openprompt/pipeline_base.py", line 101, in __init__
    self.tokenize()
  File "/home/oryza/playground/OpenPrompt/openprompt/pipeline_base.py", line 137, in tokenize
    inputfeatures = InputFeatures(**self.tokenizer_wrapper.tokenize_one_example(wrapped_example, self.teacher_forcing), **wrapped_example[1]).to_tensor()
AttributeError: 'T5Tokenizer' object has no attribute 'tokenize_one_example'
```

This is my pip list:
```
Package            Version   Editable project location
------------------ --------- ---------------------------------
aiohttp            3.8.1
aiosignal          1.2.0
async-timeout      4.0.2
asynctest          0.13.0
attrs              21.4.0
certifi            2021.10.8
charset-normalizer 2.0.12
click              8.1.2
datasets           2.0.0
dill               0.3.4
filelock           3.6.0
frozenlist         1.3.0
fsspec             2022.3.0
huggingface-hub    0.5.1
idna               3.3
importlib-metadata 4.11.3
joblib             1.1.0
multidict          6.0.2
multiprocess       0.70.12.2
nltk               3.7
numpy              1.21.5
openprompt         1.0.0     /home/oryza/playground/OpenPrompt
packaging          21.3
pandas             1.3.5
pip                22.0.4
protobuf           3.20.0
pyarrow            7.0.0
pyparsing          3.0.8
python-dateutil    2.8.2
pytz               2022.1
PyYAML             6.0
regex              2022.3.15
requests           2.27.1
responses          0.18.0
rouge              1.0.0
sacremoses         0.0.49
scikit-learn       1.0.2
scipy              1.7.3
sentencepiece      0.1.96
setuptools         41.2.0
six                1.16.0
sklearn            0.0
tensorboardX       2.5
threadpoolctl      3.1.0
tokenizers         0.10.3
torch              1.11.0
tqdm               4.64.0
transformers       4.10.0
typing_extensions  4.1.1
urllib3            1.26.9
xxhash             3.0.0
yacs               0.1.8
yarl               1.7.2
zipp               3.8.0
```

Do you have any idea about the error? I read in another thread about installing SentencePiece to solve this problem but my sentencepiece is already there.

Thank you in advance!

Best,
Oryza

**Comment by ShengdingHu** [comment]
It seems that you haven't wrap T5 with the tokenizer_wrapper

**Comment by ningding97** [comment]
> Hi,
> 
> thank you for your amazing work to ease the users of prompt learning.
> 
> I tried to implement the LMBFF tutorial and happened to meet this error:
> 
> ```
> Traceback (most recent call last):
>   File "run_lmbff.py", line 116, in <module>
>     dataloader = PromptDataLoader(dataset['train'], template, template_generate_tokenizer, template_tokenizer_wrapper, batch_size=len(dataset['train']), decoder_max_length=128) # register all data at once
>   File "/home/oryza/playground/OpenPrompt/openprompt/pipeline_base.py", line 101, in __init__
>     self.tokenize()
>   File "/home/oryza/playground/OpenPrompt/openprompt/pipeline_base.py", line 137, in tokenize
>     inputfeatures = InputFeatures(**self.tokenizer_wrapper.tokenize_one_example(wrapped_example, self.teacher_forcing), **wrapped_example[1]).to_tensor()
> AttributeError: 'T5Tokenizer' object has no attribute 'tokenize_one_example'
> ```
> 
> This is my pip list:
> 
> ```
> Package            Version   Editable project location
> ------------------ --------- ---------------------------------
> aiohttp            3.8.1
> aiosignal          1.2.0
> async-timeout      4.0.2
> asynctest          0.13.0
> attrs              21.4.0
> certifi            2021.10.8
> charset-normalizer 2.0.12
> click              8.1.2
> datasets           2.0.0
> dill               0.3.4
> filelock           3.6.0
> frozenlist         1.3.0
> fsspec             2022.3.0
> huggingface-hub    0.5.1
> idna               3.3
> importlib-metadata 4.11.3
> joblib             1.1.0
> multidict          6.0.2
> multiprocess       0.70.12.2
> nltk               3.7
> numpy              1.21.5
> openprompt         1.0.0     /home/oryza/playground/OpenPrompt
> packaging          21.3
> pandas             1.3.5
> pip                22.0.4
> protobuf           3.20.0
> pyarrow            7.0.0
> pyparsing          3.0.8
> python-dateutil    2.8.2
> pytz               2022.1
> PyYAML             6.0
> regex              2022.3.15
> requests           2.27.1
> responses          0.18.0
> rouge              1.0.0
> sacremoses         0.0.49
> scikit-learn       1.0.2
> scipy              1.7.3
> sentencepiece      0.1.96
> setuptools         41.2.0
> six                1.16.0
> sklearn            0.0
> tensorboardX       2.5
> threadpoolctl      3.1.0
> tokenizers         0.10.3
> torch              1.11.0
> tqdm               4.64.0
> transformers       4.10.0
> typing_extensions  4.1.1
> urllib3            1.26.9
> xxhash             3.0.0
> yacs               0.1.8
> yarl               1.7.2
> zipp               3.8.0
> ```
> 
> Do you have any idea about the error? I read in another thread about installing SentencePiece to solve this problem but my sentencepiece is already there.
> 
> Thank you in advance!
> 
> Best, Oryza

I re-run LM-BFF and didn't meet the bug, how do you obtain the ``template_tokenizer_wrapper``? You can check [here](https://github.com/thunlp/OpenPrompt/blob/e03a78074d3af2e1016eae80bce52b4a41a9fa91/openprompt/plms/__init__.py#L72) for more information.

**Comment by khairunnisaor** [comment]
Hi all, 

thank you so much for your responses! 

it was my bad because I want to run the code without the template generation part, plus I modified the code for an entity typing task. 

I've solved this error by adding the max length arguments for the `PromptDataLoader`:
```
    max_seq_length=256, decoder_max_length=3,
    batch_size=4,shuffle=True, teacher_forcing=False, predict_eos_token=False,
    truncate_method="head"
``` 
in the 
`train_dataloader = PromptDataLoader(dataset=dataset["train"], template=template, tokenizer=tokenizer, tokenizer_wrapper_class=WrapperClass)`

I have another question. So, I want to implement this framework for another language on an entity typing task. 
I included the language's tokenizer and use GPT2's config, model, and wrapper since the language-specific pre-trained model is GPT2-based. Then, I got this error when using the PromptDataLoader:

```
Traceback (most recent call last):
  File "gpt_run_entity_id.py", line 121, in <module>
    truncate_method="head")
  File "/home/oryza/playground/OpenPrompt/openprompt/pipeline_base.py", line 101, in __init__
    self.tokenize()
  File "/home/oryza/playground/OpenPrompt/openprompt/pipeline_base.py", line 137, in tokenize
    inputfeatures = InputFeatures(**self.tokenizer_wrapper.tokenize_one_example(wrapped_example, self.teacher_forcing), **wrapped_example[1]).to_tensor()
  File "/home/oryza/playground/OpenPrompt/openprompt/plms/lm.py", line 93, in tokenize_one_example
    encoder_inputs = self.add_special_tokens(encoder_inputs=encoder_inputs) # this will do nothing in GPT2 tokenizer
  File "/home/oryza/playground/OpenPrompt/openprompt/plms/utils.py", line 182, in add_special_tokens
    encoder_inputs[key] =  ((1-special_tokens_mask) * with_special_tokens - special_tokens_mask*100).tolist() # use -100 as special
ValueError: operands could not be broadcast together with shapes (27,) (25,) 
```

Is it because I use a different tokenizer that I also need to modify the wrapper?

It would be very helpful if you could share insight on this one. Thanks in advance!!

Best,
Oryza

**Comment by ningding97** [comment]
> 

I think you may need to make a few modifications to the wrapper, but I cannot exactly know what should be done solely based on your error. Maybe this Chinese application[ example](https://github.com/thunlp/OpenPrompt/blob/main/tutorial/6.1_chinese_dataset_uer_t5.py) could be helpful.

**Comment by cyl628** [comment]
> Hi,
> 
> thank you for your amazing work to ease the users of prompt learning.
> 
> I tried to implement the LMBFF tutorial and happened to meet this error:
> 
> ```
> Traceback (most recent call last):
>   File "run_lmbff.py", line 116, in <module>
>     dataloader = PromptDataLoader(dataset['train'], template, template_generate_tokenizer, template_tokenizer_wrapper, batch_size=len(dataset['train']), decoder_max_length=128) # register all data at once
>   File "/home/oryza/playground/OpenPrompt/openprompt/pipeline_base.py", line 101, in __init__
>     self.tokenize()
>   File "/home/oryza/playground/OpenPrompt/openprompt/pipeline_base.py", line 137, in tokenize
>     inputfeatures = InputFeatures(**self.tokenizer_wrapper.tokenize_one_example(wrapped_example, self.teacher_forcing), **wrapped_example[1]).to_tensor()
> AttributeError: 'T5Tokenizer' object has no attribute 'tokenize_one_example'
> ```
> 
> This is my pip list:
> 
> ```
> Package            Version   Editable project location
> ------------------ --------- ---------------------------------
> aiohttp            3.8.1
> aiosignal          1.2.0
> async-timeout      4.0.2
> asynctest          0.13.0
> attrs              21.4.0
> certifi            2021.10.8
> charset-normalizer 2.0.12
> click              8.1.2
> datasets           2.0.0
> dill               0.3.4
> filelock           3.6.0
> frozenlist         1.3.0
> fsspec             2022.3.0
> huggingface-hub    0.5.1
> idna               3.3
> importlib-metadata 4.11.3
> joblib             1.1.0
> multidict          6.0.2
> multiprocess       0.70.12.2
> nltk               3.7
> numpy              1.21.5
> openprompt         1.0.0     /home/oryza/playground/OpenPrompt
> packaging          21.3
> pandas             1.3.5
> pip                22.0.4
> protobuf           3.20.0
> pyarrow            7.0.0
> pyparsing          3.0.8
> python-dateutil    2.8.2
> pytz               2022.1
> PyYAML             6.0
> regex              2022.3.15
> requests           2.27.1
> responses          0.18.0
> rouge              1.0.0
> sacremoses         0.0.49
> scikit-learn       1.0.2
> scipy              1.7.3
> sentencepiece      0.1.96
> setuptools         41.2.0
> six                1.16.0
> sklearn            0.0
> tensorboardX       2.5
> threadpoolctl      3.1.0
> tokenizers         0.10.3
> torch              1.11.0
> tqdm               4.64.0
> transformers       4.10.0
> typing_extensions  4.1.1
> urllib3            1.26.9
> xxhash             3.0.0
> yacs               0.1.8
> yarl               1.7.2
> zipp               3.8.0
> ```
> 
> Do you have any idea about the error? I read in another thread about installing SentencePiece to solve this problem but my sentencepiece is already there.
> 
> Thank you in advance!
> 
> Best, Oryza

This is probably due to misplaced positional parameters. Already fix it.

**Comment by khairunnisaor** [comment]
Thanks for the update! 

About the wrapper problem, I think I will open a new issue to ask about how the wrapper works. 
Thank you so much for your fast and helpful responses!
