### ISSUE TITLE
Is it suitable for Chinese Tasks? Any Chinese example？

### ISSUE THREAD

**Issue by minghaochen** [thunlp/OpenPrompt#141]
Is it suitable for Chinese Tasks? Any Chinese example？

**Comment by ningding97** [comment]
> Is it suitable for Chinese Tasks? Any Chinese example？

Yes, please refer to this [example](https://github.com/thunlp/OpenPrompt/blob/main/tutorial/6.1_chinese_dataset_uer_t5.py).
