### ISSUE TITLE
An error occurred while using the latest version (1.0.0)

### ISSUE THREAD

**Issue by blacker521** [thunlp/OpenPrompt#142]
When I use ptr_template in the latest version.The following error occurred.
`TypeError: __init__() got an unexpected keyword argument 'placeholder_mapping'`
Version 0.1.1 does not have this problem.

**Comment by ningding97** [comment]
> When I use ptr_template in the latest version.The following error occurred. `TypeError: __init__() got an unexpected keyword argument 'placeholder_mapping'` Version 0.1.1 does not have this problem.

Could you provide more details? Thanks.

**Comment by blacker521** [comment]
I want to use mutli mask token like `scripts/RelationClassification/ReTACRED`
use the`ptr_template(PTRTemplate)`
But when I use the latest version,the following error occurred
`File "openprompt-1.0.0-py3.6.egg/openprompt/prompts/ptr_prompts.py"line 32, in __init__ placeholder_mapping=placeholder_mapping) TypeError: __init__() got an unexpected keyword argument 'placeholder_mapping'`
When I get to version 0.1.1, the code will be fine.

**Comment by ningding97** [comment]
> It didn't work,I tried using the `git clone` and `pip install` these two methods of installation

Weird, when I define the ``PTRTemplates``, it seems all right.
<img width="817" alt="image" src="https://user-images.githubusercontent.com/17723822/164180331-95faa05f-d094-4281-b1ec-a182be5d2d60.png">

**Comment by blacker521** [comment]
Ok,I'll try again. Thank you very much.

**Comment by blacker521** [comment]
It works! Thanks for your help!

**Comment by ningding97** [comment]
> It works! Thanks for your help!

Enjoy OpenPrompt!
