### ISSUE TITLE
Question About 1.4 Soft Template Tutorial

### ISSUE THREAD

**Issue by ArEnSc** [thunlp/OpenPrompt#145]
It says it's not trained using teacher forcing, I am guessing the LM Adapted T5 is trained using LM next sequence prediction or word?

**Comment by ShengdingHu** [comment]
In this script, we use manual verbalizers to do classification, which maps the probability on the [MASK] (for t5, it is the <extra_id_0>)  position onto the classification category. It is different from using a generation verbalizer or training a generation task, where the target words or sentence is filled into the [MASK] and trained using teacher forcing.
