### ISSUE TITLE
Applying OpenPrompt

### ISSUE THREAD

**Issue by yananchen1989** [thunlp/OpenPrompt#147]
Hi, I intend to apply the generation framework of OpenPrompt to NER task, based on your newly released dataset: https://ningding97.github.io/fewnerd/

Is there any avaliable example or related papers within this framework ? I havn't found yet.

Thanks in advance.

**Comment by ningding97** [comment]
For now, OpenPrompt supports entity typing (see this link), but not for NER, because locating the entities is not straightforward in the paradigm of prompt-learning.  We welcome PRs about the NER task, thanks!
