### ISSUE TITLE
When filling more than one mask

### ISSUE THREAD

**Issue by Michaelyangzhaohua** [thunlp/OpenPrompt#149]
Hi, the framework is great! I am trying to do some classification using it. How should I create templates and promptVerbalizers when I do some Chinese Classification tasks. Cause instead of English, the Chinese need more than masks. Is there any demo for that? 

example:
text = '{"placeholder":"text_a"}这篇文章是关于{"mask"}{"mask"}的'
label_words = {
    "1": ["财经"],
    "2": ["体育"],
    "3": ["娱乐"],
}

Or should I use PromptForGeneration for this kind of task?

**Comment by Achazwl** [comment]
see also #79

**Comment by Michaelyangzhaohua** [comment]
> 
Got it. Thanks a lot
