### ISSUE TITLE
TypeError: InputExample openprompt/prompt_base.py", line 239, in wrap_one_example

### ISSUE THREAD

**Issue by codewen77** [thunlp/OpenPrompt#154]
# 冒昧的问一下您，我在中文上使用出现这个错误请问这个是什么原因？

train_dataset = MyDataset("data/2018-2019.xlsx", "微信公众号新闻")

# 输入的dataset
input_dataset = ['快来旅游吧！石破天惊参天古树、千尺潭瀑布、禅龙峡漂流巨石龙、禅龙石天然巨石、佛在我心心形巨石、千年神龟天然石壁等。呼吸着深山的负离子、听泉声、漫步于林中，让你领略不一样的旅程']
for i in train_dataset.data_list:
    input_dataset.append(InputExample(guid=i.guid, text_a=i.text_a))

# 指定预训练模型
plm, tokenizer, model_config, WrapperClass = load_plm("bert", "../pretrained-models/bert-base-chinese")

# 定义模板
promptTemplate = ManualTemplate(
    text = '{"placeholder": "text_a"} 这是一篇关于{"mask"}的文章',
    tokenizer = tokenizer,
)
wrapped_example = promptTemplate.wrap_one_example(input_dataset[0])
print(wrapped_example)

# 定义语言器
promptVerbalizer = ManualVerbalizer(
    classes = classes,
    label_words = {
        "相关": related,
        "不相关": [''],
    },
    tokenizer = tokenizer,
)

# 定义模型
promptModel = PromptForClassification(
    template = promptTemplate,
    plm = plm,
    verbalizer = promptVerbalizer,
)

# 加载数据集
data_loader = PromptDataLoader(
        dataset = input_dataset,
        tokenizer = tokenizer,
        template = promptTemplate,
        tokenizer_wrapper_class=WrapperClass,
    )

# making zero-shot inference using pretrained MLM with prompt
promptModel.eval()
with torch.no_grad():
    for batch in data_loader:
        logits = promptModel(batch)
        # predictions would be 0, 1 for classes '相关', '不相关'
        preds = torch.argmax(logits, dim=-1)
        print(classes[preds])

**Comment by ningding97** [comment]
Could you provide more information? It seems like an issue of your data format.
