### ISSUE TITLE
NotImplementedError

### ISSUE THREAD

**Issue by Dongximing** [thunlp/OpenPrompt#157]
Hi, 

I just wondering know how to build "input example" list on my own dataset, since I called get_example, it will appear error"NotImplementedError", it seems to like your team do not finish this part,  since in data_processor.py 141 lines "raise NotImplementedError" or need I add code in this part? thanks 

Thanks for your tool

**Comment by ningding97** [comment]
Yes, DataProcessor is a base class and we recommend inheriting this class in your Processor, you can refer to [Processors of other datasets](https://github.com/thunlp/OpenPrompt/blob/main/openprompt/data_utils/lama_dataset.py).
