### ISSUE TITLE
openprompt.data_utils.InputExample

### ISSUE THREAD

**Issue by Xeisenperg** [thunlp/OpenPrompt#166]
为什么把中文文本赋值给InputExample中的text_a时，会出现中文变成Unicode编码的情况？
比如
input_example = InputExample(guid=0
                                ,text_a='昌宁县人民检察院指控'
                                ,label=0 
                            )
{
  "guid": 0,
  "label": 0,
  "meta": {},
  "text_a": "\u660c\u5b81\u53bf\u4eba\u6c11\u68c0\u5bdf\u9662\u6307\u63a7",
  "text_b": "",
  "tgt_text": null
}

**Comment by ningding97** [comment]
Hi, because Python's default encoding strategy is Unicode, you can manually set the encoding strategy (for example, utf-8) in your code.

**Comment by ChenWarlock** [comment]
这是因为inputexample在dump时默认用的ensure_ascii=True，需要改源码或者重写一个类
class MyInputExample(InputExample):
    def to_json_string(self):
        return json.dumps(self.to_dict(), indent=2, sort_keys=True, ensure_ascii=False) + "\n"
