### ISSUE TITLE
Training and Test code for the ProtoVerbalizer

### ISSUE THREAD

**Issue by s65b40** [thunlp/OpenPrompt#168]
Hi, I'm trying to follow the paper of 'ProtoVerb' recently and come across some details about the implementation. Could you provide a tutorial for prototypical verbalizer or maybe the source code of the Protoverb (it can be just any executable code and has not be with the OpenPrompt framework)?  Thank u.

**Comment by cgq15** [comment]
Hi, you can check out relevant codes in the following files:

`OpenPrompt/openprompt/prompts/prototypical_verbalizer.py`
`OpenPrompt/openprompt/protoverb_trainer.py`
`OpenPrompt/experiments/classification_proto_verbalizer.yaml`

To use ProtoVerb, execute `experiments/cli.py` and select `classification_proto_verbalizer.yaml` as config, you can also modeify the parameters.

**Comment by s65b40** [comment]
Thank you. I'll take a try.
