### ISSUE TITLE
Any tutorial for prompt template generation

### ISSUE THREAD

**Issue by lijiazheng99** [thunlp/OpenPrompt#169]
I'm trying to use the [T5TemplateGenerator](https://thunlp.github.io/OpenPrompt/modules/prompt_generator.html#t5templategenerator) to generate prompt templates on text classification tasks. However, after I initiated the T5TemplateGenerator and call the generate() function [it requires a config.template object](https://github.com/thunlp/OpenPrompt/blob/52245d523dbdfccd240e531768d0b738bbeae446/openprompt/prompt_base.py#L316). May I ask what should I load for this object, please? And do you have any tutorials for automatic prompt template generation, please?

**Comment by preke** [comment]
The LM-BFF tutorial works for me.
