### ISSUE TITLE
Links to the text classification and webnlg datasets were Broken

### ISSUE THREAD

**Issue by huchinlp** [thunlp/OpenPrompt#17]
The URLs for text classification and webnlg datasets seem to be broken. 

Also, it is necessary to add `--no-check-certificate` to the **wget** command and switch the end-of-lines to `LF`.

**Comment by ningding97** [comment]
> The URLs for text classification and webnlg datasets seem to be broken.
> 
> Also, it is necessary to add `--no-check-certificate` to the **wget** command and switch the end-of-lines to `LF`.

Thanks, there's something wrong of the Cloud drive, we will fix it soon.
