### ISSUE TITLE
Maybe a bug

### ISSUE THREAD

**Issue by FelliYang** [thunlp/OpenPrompt#185]
when I try to run the 0_basic.py code, as I printed the wrap_one_example, I get the following result.
![image](https://user-images.githubusercontent.com/38461329/183370665-3fee9eca-40d4-440d-94b9-9741ef56dbc8.png)
please notice the empty in the red rectangular. Intutively, I guess that openprompt don't want this empty. So I report this as a bug, maybe?

**Comment by Achazwl** [comment]
The empty at the beginning is intended. When concatenated, the sentence becomes `"Question: the language"`. Please notice that some tokenizers distinguish between "the" and " the", deleting the empty at the beginning will result in `"Question:the language"` if you detokenize them.
