### ISSUE TITLE
About model save

### ISSUE THREAD

**Issue by Mrwangkedong** [thunlp/OpenPrompt#189]
from the examples such as 6.1_chinese_dataset_uer_t5.py, the metho of saving model is to use torch.save(), it will save a so big model. i want konw if could we user little room to save model that is added to the pre-trained model~

**Comment by Achazwl** [comment]
you could manually save `prompt_model.template` or `prompt_model.verbalizer` separately when needed. However, in your mentioned 6.1_chinese_dataset_uer_t5.py, `manual_template` is used thus all trainable parameters are in the PLM. You can change to other templates and freeze the PLM when needed.
