### ISSUE TITLE
Does Prefix Tuning support T5 later?

### ISSUE THREAD

**Issue by fade-color** [thunlp/OpenPrompt#20]
I saw `T5's source code doens't support adding past_key_values ​​to the encoder in their code base.` in https://github.com/thunlp/OpenPrompt/blob/b8d9230c68bda242b78f7c56d3f002f1246b092c/openprompt/prompts/prefix_tuning_template.py#L18-L26 , Does this show that the prefix tuning is not compatible with T5? Will T5 will be supported later? thanks.

**Comment by ShengdingHu** [comment]
It has been fixed, see #27
