### ISSUE TITLE
TypeError: new(): invalid data type 'str'

### ISSUE THREAD

**Issue by humoxian** [thunlp/OpenPrompt#214]
仿照readme中的格式加载SST2数据集时报错（dataset的格式与readme中一致）：
`import csv
dataset = {}
dataset_path = '../TextClassification/SST-2/'
for split in ['train','dev','test']:
    dataset[split] = []
    with open(dataset_path+split+'.tsv','r',encoding='utf-8') as f:
        next(f)
        tsvreader = csv.reader(f, delimiter='\t')
        for line in tsvreader:
            input_example = InputExample(text_a=line[0],label=line[1])
            dataset[split].append(input_example)

from openprompt import PromptDataLoader
train_data_set = dataset['train']
train_dataloader = PromptDataLoader(
    dataset=train_data_set,
    tokenizer=tokenizer,
    template=promptTemplate,
    tokenizer_wrapper_class=WrapperClass,
)

import torch
#making zero-shot inference using pretrained MLM with prompt
with torch.no_grad():
    for batch in train_dataloader:
        logits = promptModel(batch)
        print(logits)
        preds = torch.argmax(logits,dim=-1)
        print(preds)
        print(classes[preds])`

**Comment by JunyuMao** [comment]
请问你是怎么解决的呢？
