### ISSUE TITLE
Question about 2.1 conditional generation

### ISSUE THREAD

**Issue by ZHUANG-jt** [thunlp/OpenPrompt#223]
When I run this code, I get the following error:
PermissionError: [Errno 13] Permission denied: '../../Generated_sentence_webnlg_gpt2_False.txt'.
After I gave the entire folder all permissions, I still didn't solve the problem

**Comment by ZHUANG-jt** [comment]
When I looked for the file, I couldn't find it

**Comment by cyl628** [comment]
Not sure in which directory you run the script. Maybe replace it with `./Generated_sentence_webnlg_gpt2_False.txt` or other file path that is permitted.
