### ISSUE TITLE
Question about the test score in tutorial/3.1_lmbff.py 

### ISSUE THREAD

**Issue by ZekaiShao25** [thunlp/OpenPrompt#227]
Hello, I ran this tutorial code implementing lmbff and the final test score was 0.5091743119266054.

This performance is too low, so I checked the evaluation score during training and the prediction results. In fact, the model scored 0.5 in each epoch, and the final prediction was all 0. Exactly, 0.509 equals to the score predicting majority as reported in the paper of lmbff.

I did not check in more detail, but apparently there is something wrong with the training of the model here.

**Comment by nirajpahari** [comment]
I also ran into the exactly same problem. All the predictions are for the same class.
