### ISSUE TITLE
FewShotSampler samples 'num_examples_total' or 'num_examples_per_label' for dev set

### ISSUE THREAD

**Issue by abdumaa** [thunlp/OpenPrompt#236]
Hi, 
The [FewShotSampler](https://github.com/thunlp/OpenPrompt/blob/main/openprompt/data_utils/data_sampler.py#L97) samples 'num_examples_total' or 'num_examples_per_label' for the dev set even if setting different values for 'num_examples_total_dev' or 'num_examples_per_label_dev'. It only works as wished if valid_dataset=None and also_sample_dev=True.

**Comment by cyl628** [comment]
Thx, we have fixed it
