### ISSUE TITLE
problem with generate() function when using PromptForGeneration with T5

### ISSUE THREAD

**Issue by isaac-murphy** [thunlp/OpenPrompt#243]
I am currently trying to do the tutorial for conditional generation from the tutorials directory. Using the tutorial code I am able to assemble the model and train it, but I run into problems when I try to generate text or when I run the tutorial's evaluate function

```
batch = next(iter(test_dataloader))
prompt_model.generate(batch, verbose = True, **generation_arguments)
```
this code returns the following error: 

> AttributeError: 'PromptForGeneration' object has no attribute 'can_generate'

if I work around that error by assigning the prompt model's `can_generate` attribute to the same value as in the prompt model's PLM, I get the next error when calling `generate()`:

> AttributeError: 'PromptForGeneration' object has no attribute 'generation_config'

I get the same errors when running the provided `evaluate` function. Am I doing something wrong? I'm trying to follow the tutorial as closely as possible. 

Versions: 
openprompt 1.0.1
transformers 4.26.1
torch 1.13.1

[colab notebook with reproduceable errors](https://colab.research.google.com/drive/18-t980NCIy2qShE-g8b1Vp_p3REfZ6jd?usp=sharing)

**Comment by shaoyuyoung** [comment]
I have the same problem. Have you solved it？

**Comment by isaac-murphy** [comment]
It seems like the problem comes from using openprompt with newer versions of huggingface. I tried again with transformers==4.20.0 and the generate function is working now
