### ISSUE TITLE
is it possible to dynamically add a soft template based on the input sentence

### ISSUE THREAD

**Issue by cmgchess** [thunlp/OpenPrompt#244]
Say I have a dataset of input sentences from domains `food`, `movies` and `songs`  
Now I need to train a soft prompt  
I want my prompt to be dynamic based on the situation  
**food** `'{"placeholder": "text_a"} {"soft": "The"} {"soft": "food"} {"soft": "was"} {"mask"}.'`  
**movies** `'{"placeholder": "text_a"} {"soft": "It"} {"soft": "is"} {"soft": "a"} {"mask"} {"soft": "movie"}.'`
**songs** `'{"placeholder": "text_a"} {"soft": "The"} {"soft": "song"} {"soft": "was"} {"mask"}.'`

Is something like this possible using OpenPrompt

**Comment by cyl628** [comment]
Currently there is no available implementation for a dynamic template. A possible workaround is to use multiple `Dataset` and use different template for each `Dataset`, then pu them together into a dataloader.
you can read methods in `PromptDataLoader` for reference 
https://github.com/thunlp/OpenPrompt/blob/8756a8cf5af4e7e01db3d612d74cb4cd1d927aba/openprompt/pipeline_base.py#L117
https://github.com/thunlp/OpenPrompt/blob/8756a8cf5af4e7e01db3d612d74cb4cd1d927aba/openprompt/pipeline_base.py#L131

**Comment by cmgchess** [comment]
@cyl628 thank you very much for the reply!
will have a look
