### ISSUE TITLE
buggy code in `mixed_template.py` ?

### ISSUE THREAD

**Issue by cmgchess** [thunlp/OpenPrompt#246]
In [`mixed_template.py`](https://github.com/thunlp/OpenPrompt/blob/c5a04d481a1d4ee87bc40eabacd9207650e25d0a/openprompt/prompts/mixed_template.py#L76)

line 76 onwards. The [docs](https://thunlp.github.io/OpenPrompt/notes/template.html#soft-mix-template) mention   

If you try to define 10000 identical soft tokens, use the key same,
`{"soft": None, "duplicate": 10000, "same": True}`

but in the [code ](https://github.com/thunlp/OpenPrompt/blob/c5a04d481a1d4ee87bc40eabacd9207650e25d0a/openprompt/prompts/mixed_template.py#L80)it tries to do `len` of an `int` .  `len(d["duplicate"])`
```python
  if "same" in d and d["same"]:
      num_soft_token += 1
      id_list = [num_soft_token for _ in range(len(d["duplicate"]))]
  else:
      num_soft_token += d["duplicate"]
      id_list = list(range(old_num+1, num_soft_token+1))
```

possible bug?

**Comment by cyl628** [comment]
Thx! The bug has been fixed.
