### ISSUE TITLE
a question about soft_template

### ISSUE THREAD

**Issue by ghbtest** [thunlp/OpenPrompt#247]
in the Doc it says, "if you use {'soft'}, the token will be randomly initialized. If you add some textual tokens at the value position, the soft token(s) will be initialized by these tokens.", then for most soft_template examples in the repo, e.g.
scripts/SuperGLUE/CB/soft_template.txt
scripts/SuperGLUE/RTE/soft_template.txt
scripts/SuperGLUE/BoolQ/soft_template.txt
no "soft" marker is seen. so how exactly should a soft_template be defined?

**Comment by cyl628** [comment]
Hi, sorry for the confusion. You are correct, the three template files you mentioned are actually not **soft** templates. As for how to define a soft template, you can refer to 
scripts/FewGLUE/RTE/soft_manual_template.txt
scripts/TextClassification/agnews/mixed_template.txt
as examples for randomly initialized soft tokens and soft tokens initialized by textual tokens.
