### ISSUE TITLE
How to return the cls characteristics of the model in the classification task

### ISSUE THREAD

**Issue by wangqian97** [thunlp/OpenPrompt#249]
Hello, I want to get the cls characteristics of PLM output, the size is (batch,hidden_size), I would like to modify the code return value in verbalizer.process_outputs, can you tell me the specific method? thank you

**Comment by cyl628** [comment]
Hi, I am not sure OpenPrompt is the suitable package to use if you are only using cls characteristics while leaving the whole verbalizer module out. Maybe you can directly use the (`transformers` library)[https://huggingface.co/docs/transformers/index]
