### ISSUE TITLE
Some questions about prompt tuning

### ISSUE THREAD

**Issue by shaoyuyoung** [thunlp/OpenPrompt#267]
hello,

Thanks for your useful work.

I have some questions about `prompt tuning`.

In #135, one of contributors said that `soft prompt + freeze model = prompt tuning`.

But I want to know if I just use `soft prompt` and set `freeze model==False`. Is it also should be called `prompt-tuning`?

Thanks in advance

**Comment by ningding97** [comment]
This is a subjective question, and I think we should not be entangled with this issue. Technically, the original paper on prompt tuning particularly emphasizes that the model should be frozen. This is more like a "parameter-efficient tuning" method rather than a "prompt-learning" method.

**Comment by shaoyuyoung** [comment]
Thanks a lot
