### ISSUE TITLE
The `max_length` of  `model.generate()`

### ISSUE THREAD

**Issue by shaoyuyoung** [thunlp/OpenPrompt#269]
Sorry to bother you again.

When I use openprompt, I meet this userwarning: 
```
UserWarning: Neither `max_length` nor `max_new_tokens` has been set, `max_length` will default to 20 (`generation_config.max_length`).  
 Controlling `max_length` via the config is deprecated and `max_length` will be removed from the config in v5 of Transformers   
-- we recommend using `max_new_tokens` to control the maximum length of the generation.
```

I think I have set the `decoder_max_length` in adavance.

I am sorry that limited by my code level, I am not sure whether maximum model generated length is set in the `generate()` method? But if `**batch` contains the `max_length`. Why do user warnings appear here

https://github.com/thunlp/OpenPrompt/blob/2aa42a071b1166db4b6c7cc60c580c1f1ed94e5d/openprompt/pipeline_base.py#L512

Thx in adavance!

**Comment by ODDHOOD** [comment]
你好！！ 我用T5-large生成的句子总是会被截断，你找到什么方法可以控制生成长度的吗？谢谢你的解答

**Comment by shaoyuyoung** [comment]
My final solution was to process the original input, keeping the length of the original tokens as small as possible to 512

It seems that the PLMs only support 512 as the maximum length

**Comment by ODDHOOD** [comment]
你好 你的问题不是输出的长度会受限制吗 你现在回答是输入会截断吧 我的困扰是 我的预测输出的句子总是很短 不完整 你遇到这样的问题吗 怎样解决的呀 谢谢你


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "thunlp/OpenPrompt"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月25日(星期五) 下午3:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [thunlp/OpenPrompt] The `max_length` of  `model.generate()` (Issue #269)





 
My final solution was to process the original input, keeping the length of the original tokens as small as possible to 512
 
It seems that the PLMs only support 512 as the maximum length
