### ISSUE TITLE
Needing Tutorial for Generation Task

### ISSUE THREAD

**Issue by RecklessRonan** [thunlp/OpenPrompt#28]
Hi, thanks for your excellent work.  

I'm trying to apply OpenPrompt to generation task, but I have no idea.

If possible, could you provide a tutorial for generation task, like the tutorial of classification task in the readme?

Thanks anyway!

**Comment by ShengdingHu** [comment]
We have added some tutorials about the conditional generation (but the hyper-parameters haven't been carefully chosen). Feel free to try them!
