### ISSUE TITLE
example and tutorial for PTRTemplate

### ISSUE THREAD

**Issue by lihuiliullh** [thunlp/OpenPrompt#284]
Can you give some examples or tutorial for PTRTemplate? @ningding97

**Comment by Achazwl** [comment]
https://github.com/thunlp/OpenPrompt/blob/main/experiments/relation_classification_ptr.yaml

**Comment by lihuiliullh** [comment]
Thanks for the reply. May I know where to download TACRED? @Achazwl

**Comment by Achazwl** [comment]
https://nlp.stanford.edu/projects/tacred/#access
