### ISSUE TITLE
Please consider adding a todo or not implemented list on the home page

### ISSUE THREAD

**Issue by Raibows** [thunlp/OpenPrompt#3]
Some features such as Conditional Generation are missing or not easy to use, I have to manually edit the source code.  And the docs are under constructing.  Maybe adding a beta tag or list the not implemented features is a better way for the users.
Really thanks for sharing the code for prompt learning.

**Comment by ShengdingHu** [comment]
Thanks for the suggestion! We are indeed on the way of adding features and making them easier to use. We have added a beta icon in the previous release. Currently, the conditional generation can be run using the experiments/generation_{manual_template/prefixtuning}.yaml. However, some advanced sampling modes, and other tricks and datasets haven't be implemented. A more user-friendly version of generation utilities will be available soon!

**Comment by Raibows** [comment]
Looking forward to it!
