### ISSUE TITLE
openprompt.prompt_base.py中存在一个小bug

### ISSUE THREAD

**Issue by 161220012** [thunlp/OpenPrompt#31]
我在跟着readme走到Step 3: Define a Template的时候发现一个bug：示例中定义的text = ["<text_a>", "It", "was", "<mask>"], 然而在openprompt.prompt_base.py中第168行此时的text[i:j]是一个list，不存在rstrip(' ')属性

**Comment by ShengdingHu** [comment]
Sorry, the readme has been outdated, we will update it soon.
