### ISSUE TITLE
Question about updating the repository

### ISSUE THREAD

**Issue by probe2** [thunlp/OpenPrompt#43]
How do you keep this repository up to date? Do I need to clone the entire library every time and update it again as follows:

```
git clone https://github.com/thunlp/OpenPrompt.git
cd OpenPrompt
pip install -r requirements.txt
python setup.py install
```

**Comment by huchinlp** [comment]
Just replace the last line to:
`pip install -e .`

**Comment by probe2** [comment]
> 
> 
> Just replace the last line with `pip install -e .`

Thank you for your reply, one more question, did you test the experimental results of the code you wrote like the tutorial?

**Comment by huchinlp** [comment]
I tested most configurations for the classification task provided in the `experiments` directory and they worked well.

**Comment by probe2** [comment]
> 
> 
> I tested most configurations for the classification task provided in the `experiments` directory and they worked well.

How about the generation tasks? such as the application of prefix-tuning in webnlg

**Comment by probe2** [comment]
How about the generation tasks? such as the application of prefix-tuning in webnlg

**Comment by BrettFyt** [comment]
Hello，have you ever used gpt2 for prompt test？If I want to output mask after the input，it will show "IndexError:index is out of bounds for dimension with size 0".
For example：
`promptTemplate = ManualTemplate(
            text = '{"placeholder":"text_a"} {"mask"}' ,
            tokenizer = tokenizer
        )`
        `promptVerbalizer = ManualVerbalizer(
            classes = classes,
            label_words = {
                "1": ["one"],
                "2": ["two"],
                "3": ["three"]
            },
            tokenizer = tokenizer
        )`
