### ISSUE TITLE
P-Tuning template has not been adapted to new version ?

### ISSUE THREAD

**Issue by Doragd** [thunlp/OpenPrompt#45]
**Does the P-Tuning template seem to still use the old format?**
![image](https://user-images.githubusercontent.com/26213546/140937254-453f5e99-4d48-4465-9295-05e391d90bf5.png)

**Comment by ningding97** [comment]
> **Does the P-Tuning template seem to still use the old format?**
> ![image](https://user-images.githubusercontent.com/26213546/140937254-453f5e99-4d48-4465-9295-05e391d90bf5.png)



> **Does the P-Tuning template seem to still use the old format?**
> ![image](https://user-images.githubusercontent.com/26213546/140937254-453f5e99-4d48-4465-9295-05e391d90bf5.png)

Yea we will publish a pypi version in about 2-3 weeks, by then all the old parts will be updated. (ACL ddl is approaching lol).  PRs are also welcomed!

**Comment by Doragd** [comment]
Sorry to bother you again. I have checked the latest version. However, the p-tuning template seems not to be changed.  I would like to know if there are any results of using p-tuning template on FewGLUE_32dev.

**Comment by Achazwl** [comment]
The code of the template format is updated now in the latest commit a478a28 on master.

**Comment by Doragd** [comment]
Thanks, @Achazwl.
