### ISSUE TITLE
Call for Correct and Systematic Documentation

### ISSUE THREAD

**Issue by zhaone** [thunlp/OpenPrompt#46]
```python
from openprompt import PromptForClassification
promptModel = PromptForClassification(
    template = promptTemplate,
    model = bertModel,
    verbalizer = promptVerbalizer,
)
```
Hi, I tried to follow the readme and I got the following err:
```shell
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-11-6ad90754910f> in <module>
      1 from openprompt import PromptForClassification
----> 2 promptModel = PromptForClassification(
      3     template = promptTemplate,
      4     model = bertModel,
      5     verbalizer = promptVerbalizer,

TypeError: __init__() got an unexpected keyword argument 'model'
```
After searching through your code, I rectify arg `model` to `plm`.

However, to avoid frequent mistakes in the future, I want to know if you have correct and systematic documentation that can help me?

**Comment by zhaone** [comment]
OK, https://github.com/thunlp/OpenPrompt/tree/main/tutorial is a good tutorial for me, thanks.

**Comment by ningding97** [comment]
> OK, https://github.com/thunlp/OpenPrompt/tree/main/tutorial is a good tutorial for me, thanks.

Let the bullet fly 😄
