### ISSUE TITLE
使用 InputExample() 构建中文数据集，汉字读入为Unicode编码

### ISSUE THREAD

**Issue by terence1023** [thunlp/OpenPrompt#49]
Code
```python
dataset = {}
dataset["train"] = []
for index,data in train_dataset.iterrows():
    input_example = InputExample(text_a = data["text"], label=data["class"], guid=data["id"])
    dataset["train"].append(input_example)
print(dataset["train"][10])
```
output
```python
{
  "guid": 13,
  "label": 2,
  "meta": {},
  "text_a": "\u522b\u6025\u3002\u8bf4\u4e0d\u51c6\u7684\u3002\u7b2c\u4e00\u6b21\u8fc7\u7684\u65f6\u5019\u4e5f\u5ba1\u6838\u4e86\u5341\u51e0\u5929\u3002\u4e0d\u8fc7\u6700\u540e\u5168\u989d\u5ea6\u901a\u8fc7\u3002\u5229\u606f\u9ad8\u5c31\u6ca1\u7528",
  "text_b": "",
  "tgt_text": null
}
```

**Comment by ShengdingHu** [comment]
Encoding issues should be addressed by the user himself. For example, use the corresponding encoding when loading the dataset files. `InputExample` only build inputs from loaded datasets.

**Comment by ChenWarlock** [comment]
重写类，默认用ensure_ascii=True
class MyInputExample(InputExample):
    def to_json_string(self):
        return json.dumps(self.to_dict(), indent=2, sort_keys=True, ensure_ascii=False) + "\n"

**Comment by pony-m** [comment]
> 重写类，默认用ensure_ascii=True class MyInputExample(InputExample): def to_json_string(self): return json.dumps(self.to_dict(), indent=2, sort_keys=True, ensure_ascii=False) + "\n"

请问是要用户自己写呀还是已经更新到代码里啦，我也遇到此问题，但好像不影响代码跑通

**Comment by ChenWarlock** [comment]
> 

我用的是1.0.0，可以直接找到源代码进行修改，或者自己重写一个json的dump函数。不过去修改源代码是最方便的。跑通肯定可以，但是变成Unicode编码可能分词会出现问题，可能会影响效果吧。源码应该是再openprompt/data_utils/utils.py，修改InputExample类里面的to_json_string，改成return json.dumps(self.to_dict(), indent=2, sort_keys=True, ensure_ascii=False) + "\n"

**Comment by pony-m** [comment]
感谢回复~
我想自动搜索生成模板，请问源代码有设计接口嘛~
另外，是否有其他下游任务的示例代码呀，目前 0_basic.py 是针对情感分析任务，其他py文件都没有对应具体下游任务，希望能有文本分类、问答、摘要生成等任务的示例代码
















在 2022-08-09 20:29:04，"ChenWarlock" ***@***.***> 写道：

我用的是1.0.0，可以直接找到源代码进行修改，或者自己重写一个json的dump函数。不过去修改源代码是最方便的。跑通肯定可以，但是变成Unicode编码可能分词会出现问题，可能会影响效果吧。源码应该是再openprompt/data_utils/utils.py，修改InputExample类里面的to_json_string，改成return json.dumps(self.to_dict(), indent=2, sort_keys=True, ensure_ascii=False) + "\n"

**Comment by ChenWarlock** [comment]
> 感谢回复~ 我想自动搜索生成模板，请问源代码有设计接口嘛~ 另外，是否有其他下游任务的示例代码呀，目前 0_basic.py 是针对情感分析任务，其他py文件都没有对应具体下游任务，希望能有文本分类、问答、摘要生成等任务的示例代码 在 2022-08-09 20:29:04，"ChenWarlock" ***@***.***> 写道： 我用的是1.0.0，可以直接找到源代码进行修改，或者自己重写一个json的dump函数。不过去修改源代码是最方便的。跑通肯定可以，但是变成Unicode编码可能分词会出现问题，可能会影响效果吧。源码应该是再openprompt/data_utils/utils.py，修改InputExample类里面的to_json_string，改成return json.dumps(self.to_dict(), indent=2, sort_keys=True, ensure_ascii=False) + "\n" — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

自动生成模板可以参考tutorial/3.1_LMBFF.py，这里面给出了可以生成模板的示例，但是会占很多gpu内存（具体多少忘记了，可能20g起步吧）。其他下游任务的话，目前也就尝试了多分类和多标签，其他任务感觉就目前来说可能prompt还不是很成熟。序列标注倒是可以做，但是训练时间会比fine-tune长很多。由于我现在是个实习生，代码是在公司写的，我也不知道能不能放出来，所以emmmmm。总之，就目前来说，prompt更适合做分类型的任务，而且可能对中文支持不是很友好。
可以参考https://github.com/Clearailhc/Openprompt-learner，这里面有生成式的使用，希望有用。
ps：我也只是一位使用者
