### ISSUE TITLE
Does T5 have model-parallel interface support for multi-gpu training?

### ISSUE THREAD

**Issue by TheMrYang** [thunlp/OpenPrompt#52]

**Comment by ShengdingHu** [comment]
Yes, please pay attention to [parallelize](https://github.com/thunlp/OpenPrompt/blob/9fcbd9f8dd1e6de439ea70b1fe7b7da789d09b67/openprompt/pipeline_base.py#L300) and [deparallelize](https://github.com/thunlp/OpenPrompt/blob/9fcbd9f8dd1e6de439ea70b1fe7b7da789d09b67/openprompt/pipeline_base.py#L311) methods.
