### ISSUE TITLE
发现一个文档过时

### ISSUE THREAD

**Issue by NLPpupil** [thunlp/OpenPrompt#54]
https://thunlp.github.io/OpenPrompt/notes/examples.html， step 5。
PromptForClassification.__init__函数已经没有keyword参数了。

**Comment by NLPpupil** [comment]
https://thunlp.github.io/OpenPrompt/notes/examples.html，这里可能还有其他过时的地方，可否整体再过一遍这篇Introduction？

**Comment by ningding97** [comment]
> https://thunlp.github.io/OpenPrompt/notes/examples.html，这里可能还有其他过时的地方，可否整体再过一遍这篇Introduction？

Thanks, we will update the entire doc soon. 
Please use English so that everyone could understand your issue.
