### ISSUE TITLE
tutorial 0 basic.py 没有使用 model_inputs

### ISSUE THREAD

**Issue by gaoisbest** [thunlp/OpenPrompt#56]
第 68 行定义了 [model_inouts](https://github.com/thunlp/OpenPrompt/blob/main/tutorial/0_basic.py#L68), 但是后面并没有使用它，是不是有问题

**Comment by ShengdingHu** [comment]
Translation: 
Q:  Line 68 defines `model_inouts`, but it is not used later, is there a problem?
A:  Line 68-73 shows the example of preparing model_inputs by yourself, which is fully covered by using Prompt DataLoader, therefore `model_inputs` is not in use in the codes behind.
