### ISSUE TITLE
Documentation should be updated...

### ISSUE THREAD

**Issue by ZenMoore** [thunlp/OpenPrompt#61]
The usage example in README.md is not runnable.
And the code is much different from the documentation.

**Comment by ShengdingHu** [comment]
The code in the README.md is directly runnable. The output is as follow. Could you provide more details about your issue?
<img width="320" alt="image" src="https://user-images.githubusercontent.com/32740627/143519976-2cff0c12-af10-45e6-89d7-ff944d1280c7.png">
