### ISSUE TITLE
Possible omission {"soft"} in in mix template

### ISSUE THREAD

**Issue by Bhardwaj-Rishabh** [thunlp/OpenPrompt#64]
Really appreciate the work!

It seems the mixed_template.py is ignoring the `{"soft"}` string.

As I find the following two mixed templates produce the same 'input_ids':

Template1 text
`'{"placeholder":"text_a"} {"soft":"The"} {"soft"} {"soft":"the"} {"placeholder":"text_b"} {"soft"} {"mask"}.')
`

Template2 text
`'{"placeholder":"text_a"} {"soft":"The"} {"soft":"the"} {"placeholder":"text_b"}{"mask"}.'
`

Input ids for both the above templates is:

`{"input_ids": [[27, 183, 13802, 0, 0, 27, 174, 12, 3, 1544, 32099, 3, 5, 1, 0, 0 ...}
`

Note:
```
text_a = "I am hungry"
text_b = "I need to eat"

```

PS: It might also be ignoring its id from 'soft_token_ids'

Thanks!

**Comment by Achazwl** [comment]
Sorry for the bug. It was fixed in cc8278ad, and it's now merged into origin/main. You can try it. If there're still problems, please tell us.
