### ISSUE TITLE
Confused about the type hint of ManualVerbalizer.__init__

### ISSUE THREAD

**Issue by NLPpupil** [thunlp/OpenPrompt#67]
The type hint of ManualVerbalizer.__init__ includes:
```python
label_words (:obj:`Union[Sequence[str], Mapping[str, str]]`, optional): The label words that are projected by the labels.
```
However, I found two cases where the type of label_words is neither Sequence[str] or Mapping[str, str].

In [Introduction with an Example](https://thunlp.github.io/OpenPrompt/notes/examples.html), 
```python
from openprompt.prompts import ManualVerbalizer
promptVerbalizer = ManualVerbalizer(
    classes = classes,
    label_words = {
        "negative": ["bad"],
        "positive": ["good", "wonderful", "great"],
    },
    tokenizer = tokenizer,
)
```

In [0_basic.py](https://github.com/thunlp/OpenPrompt/blob/main/tutorial/0_basic.py),
```python
myverbalizer = ManualVerbalizer(tokenizer, num_classes=2, 
                        label_words=[["yes"], ["no"], ["maybe"]])
```

**Comment by ShengdingHu** [comment]
Thank you for pointing out this issue. It has been fixed in [commit](https://github.com/thunlp/OpenPrompt/commit/675545ce1f946aa186efda8e8640dbc29fd1159f).
