### ISSUE TITLE
How to config `num_classes` parameter of Verbalizer?

### ISSUE THREAD

**Issue by NLPpupil** [thunlp/OpenPrompt#69]
In [0_basic.py](https://github.com/thunlp/OpenPrompt/blob/main/tutorial/0_basic.py):
```
myverbalizer = ManualVerbalizer(tokenizer, num_classes=2, 
                        label_words=[["yes"], ["no"], ["maybe"]])
```
Why could len(label_words) > num_classes?  what if len(label_words) < num_classes?

**Comment by ShengdingHu** [comment]
Sorry, it is a mistake, we will move the length check from the from_file method into the setter method of the label words soon.

**Comment by abcdhhhh** [comment]
In [1.1_mixed_template.py](https://github.com/thunlp/OpenPrompt/blob/main/tutorial/1.1_mixed_template.py) also.

**Comment by ningding97** [comment]
> In [1.1_mixed_template.py](https://github.com/thunlp/OpenPrompt/blob/main/tutorial/1.1_mixed_template.py) also.

Fixed, thanks
