### ISSUE TITLE
中文xlnet 和 bert 报错

### ISSUE THREAD

**Issue by wym888** [thunlp/OpenPrompt#71]
会提示添加  encoder_inputs[key] =  ((1-special_tokens_mask) * with_special_tokens - special_tokens_mask*100).tolist() 无法广播我代码如下
plm=AutoModel.from_pretrained(xlnet_path)
tokenizer=AutoTokenizer.from_pretrained(xlnet_path)
model_config=AutoConfig.from_pretrained(xlnet_path,output_attentions=True, foo=False, return_unused_kwargs=True)
WrapperClass=MLMTokenizerWrapper

**Comment by ningding97** [comment]
Could you please provide more details about this issue?
