### ISSUE TITLE
relation classification results 

### ISSUE THREAD

**Issue by mk2x15** [thunlp/OpenPrompt#72]
Hi, may I know the performance of prompt learning on the relation classification task? I didn't find them, thanks.

**Comment by ningding97** [comment]
Hi, there are several works focusing on this topic such as [PTR](https://arxiv.org/abs/2105.11259), we also implement PTR in OpenPrompt and the performance is close to the original paper. More papers could be found [here](https://github.com/thunlp/PromptPapers).
