### ISSUE TITLE
ModuleNotFoundError: No module named 'yacs'

### ISSUE THREAD

**Issue by cindyhi** [thunlp/OpenPrompt#73]
from yacs.config import CfgNode
ModuleNotFoundError: No module named 'yacs'

**Comment by Doragd** [comment]
`pip install yacs`

**Comment by ningding97** [comment]
> from yacs.config import CfgNode ModuleNotFoundError: No module named 'yacs'

It turns out the pip package of openprompt did not automatically install all the dependencies, fixed now.
