### ISSUE TITLE
How to do data parallelism with multi-gpus?

### ISSUE THREAD

**Issue by ZikaiGuo** [thunlp/OpenPrompt#76]
Hi, I'm using T5 and PromptForGeneration class. Currently model parallelism is supported but it seems that data parallelism is not supported.

I try to use torch DDP and Accelerator to do data parallelism with multi-gpus. But it seems to me that PromptForGeneration do not support DDP.

Such codes would fail:
model = PromptForGeneration(xxx)
torch.nn.parallel.DistributedDataParallel(model)

Error info is:

  File "/root/miniconda3/lib/python3.9/site-packages/accelerate/accelerator.py", line 294, in prepare_model
    model = torch.nn.parallel.DistributedDataParallel(
  File "/root/miniconda3/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 498, in __init__
    self._sync_params_and_buffers(authoritative_rank=0)
  File "/root/miniconda3/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 514, in _sync_params_and_buffers
    self._distributed_broadcast_coalesced(
  File "/root/miniconda3/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 1278, in _distributed_broadcast_coalesced
    dist._broadcast_coalesced(
TypeError: _broadcast_coalesced(): incompatible function arguments. The following argument types are supported:
    1. (process_group: torch._C._distributed_c10d.ProcessGroup, tensors: List[at::Tensor], buffer_size: int, src: int = 0) -> None

I check functions of DDP and find that PromptForGeneration cannot use DDP to do data parallelism because its state_dict is changed. In pipeline_base.py line 603, state_dict consists of state_dict['plm'] and state_dict['template']. That leads to the TypeError below.  DDP module expect list(state_dict.values()) to be list of tensor. But it get list of OrderedDict instead, when using PromptForGeneration.

Do open prompt currently support data parallelism? Would you consider to add this feature?

**Comment by ShengdingHu** [comment]
Thank you for testing this feature. We will add this feature recently. Before that, we suggest you rewrite the state_dict related methods as a work-around.
