### ISSUE TITLE
Typing Mistake

### ISSUE THREAD

**Issue by HenryCai11** [thunlp/OpenPrompt#77]
The parameter **text** in class `PTRTemplate` -> method `__init__()` should be `Optional[List[str]]`. It's an insignificant issue, though 🤣

**Comment by HenryCai11** [comment]
Sorry to bother, I just realize that all relation prompts share the same template! Btw, have you ever tried to use multiple templates for a single relation? Because by instinctively, there may be several combinations of logic rules that can induce the expected relation. 😆

**Comment by ningding97** [comment]
> Sorry to bother, I just realize that all relation prompts share the same template! Btw, have you ever tried using multiple templates for a single relation? Because instinctively, there may be several combinations of logic rules that can induce the expected relation. 😆

Hi, multiple templates for a single relation could be regarded as an ensembling method, which is proven to be effective in some settings. We encourage you to explore versatile applications on OpenPrompt!

**Comment by ningding97** [comment]
> The parameter **text** in class `PTRTemplate` -> method `__init__()` should be `Optional[List[str]]`. It's an insignificant issue, though 🤣

Thanks, we will fix it soon~

**Comment by HenryCai11** [comment]
> > Sorry to bother, I just realize that all relation prompts share the same template! Btw, have you ever tried using multiple templates for a single relation? Because instinctively, there may be several combinations of logic rules that can induce the expected relation. 😆
> 
> Hi, multiple templates for a single relation could be regarded as an ensembling method, which is proven to be effective in some settings. We encourage you to explore versatile applications on OpenPrompt!

Thanks for encouraging! I am recently working on PTR and trying to reproduce it with OpenPrompt. 😆 And I just found another issue. 🤣  The slot `placeholder_mapping` in the constructor of class `PtuningTemplate` is missing.

**Comment by ningding97** [comment]
> > > Sorry to bother, I just realize that all relation prompts share the same template! Btw, have you ever tried using multiple templates for a single relation? Because instinctively, there may be several combinations of logic rules that can induce the expected relation. 😆
> > 
> > 
> > Hi, multiple templates for a single relation could be regarded as an ensembling method, which is proven to be effective in some settings. We encourage you to explore versatile applications on OpenPrompt!
> 
> Thanks for encouraging! I am recently working on PTR and trying to reproduce it with OpenPrompt. 😆 And I just found another issue. 🤣 The slot `placeholder_mapping` in the constructor of class `PtuningTemplate` is missing.

Thanks! We will check it out and fix it soon.
