### ISSUE TITLE
How to handle label words in Chinese?

### ISSUE THREAD

**Issue by NLPpupil** [thunlp/OpenPrompt#79]
Label words may be tokenized into multiple tokens. In Chinese, label words are likely be tokenized into characters. 
So, how to handle label words that consist of more than one characters?

**Comment by Achazwl** [comment]
You can try the below methods:
- use label word appeared in the vocabulary, for example, using option format for classification:
 `文本：xxx 问题： xxx? 选项：1、长标签 2、另一个长标签. 回答：`
then use `1, 2` as label words, which has a high probability of appearing in the vocabulary
- use generation form, refer to tutorial/4.1

**Comment by NLPpupil** [comment]
Your solutions are really smart. Thank you. I will try them later.

**Comment by NLPpupil** [comment]
@Achazwl Your solutions are really smart. Thank you. I will try them later.

**Comment by lonelydancer** [comment]
> * `文本：xxx 问题： xxx? 选项：1、长标签 2、另一个长标签. 回答：`
>   then use `1, 2` as label words, which has a high probability of appearing in the vocabulary

如果 分类有几十个呢。方法一 会出现 两位数，tokenize的时候还会切开。

**Comment by zgjiangtoby** [comment]
Hi, is there any working example or tutorial for how to write PTRtemplate and PTRverbalizer? This would be nice to those multi-label classification users! Thanks

> https://github.com/thunlp/OpenPrompt/blob/main/openprompt/prompts/ptr_prompts.py could handle multiple masks. Or https://github.com/thunlp/OpenPrompt/blob/main/tutorial/4.1_all_tasks_are_generation.py may be possible.

**Comment by Zeng1998** [comment]
Any update?
