### ISSUE TITLE
can you add a tutorial python file  about  the Relation Classification

### ISSUE THREAD

**Issue by buaadk** [thunlp/OpenPrompt#81]
TACRED dataset or the SemEval dataset

**Comment by ningding97** [comment]
> TACRED dataset or the SemEval dataset

Hi, for now, there are no tutorials for relation classification, but you can refer to this [link](https://github.com/thunlp/OpenPrompt/blob/main/experiments/relation_classification_ptr.yaml) to conduct experiments. And we also provide templates for the three datasets. Welcome to submit PRs if you are interested in contributing to the RC tutorial.
