### ISSUE TITLE
bminf

### ISSUE THREAD

**Issue by hl0929** [thunlp/OpenPrompt#83]
Excuse me, which version did bminf use?

**Comment by ningding97** [comment]
Hi, you can use CPM with bminf by [this](https://github.com/thunlp/OpenPrompt/blob/main/tutorial/5.1_BMInf_CPM.py) tutorial.

**Comment by Achazwl** [comment]
The way to how to install BMInf and use it with OpenPrompt is written in the file tutorial/5.1 in the latest origin/dev.
This is a feature that is not fully online, you can use `git pull` to update the repo and give us some feedback if you like.
