### ISSUE TITLE
AttributeError: 'PtuningTemplate' object has no attribute 'prompt_encoder_type'

### ISSUE THREAD

**Issue by fade-color** [thunlp/OpenPrompt#84]
When the ptuningtemplate is initialized, the text parameter is passed in, and will be called `on_text_set` method, and then in `generate_ parameters`：https://github.com/thunlp/OpenPrompt/blob/fe7f4cbb719e796311973c882883773c8306c4b2/openprompt/prompts/ptuning_prompts.py#L48-L52
The `prompt_encoder_type` variable is accessed in the 50th line of the `generate_parameters` method, and `prompt_encoder_type` has not yet been assigned at this time.

**Comment by Achazwl** [comment]
Fixed in the latest main branch.
