### ISSUE TITLE
Error in tutorial/3.1_LMBFF.py 

### ISSUE THREAD

**Issue by shenxianhu** [thunlp/OpenPrompt#89]
when i runned tutorial/3.1_LMBFF.py, there was an error, as follow:

Traceback (most recent call last):
  File "tutorial/3.1_LMBFF.py", line 118, in <module>
    dataloader = PromptDataLoader(dataset['train'], template, template_generate_tokenizer, template_tokenizer_wrapper, batch_size=len(dataset['train'])) # register all data at once
  File "./openprompt/pipeline_base.py", line 92, in __init__
    self.tokenize()
  File "./openprompt/pipeline_base.py", line 131, in tokenize
    inputfeatures = InputFeatures(**self.tokenizer_wrapper.tokenize_one_example(wrapped_example, self.teacher_forcing), **wrapped_example[1]).to_tensor()
  File "./openprompt/plms/seq2seq.py", line 51, in tokenize_one_example
    wrapped_example, others = wrapped_example
  File "./openprompt/plms/seq2seq.py", line 132, in truncate_decoder_inputs
    inputs = self.padding(inputs, max_len = self.decoder_max_length, pad_id_for_inputs=self.tokenizer.pad_token_id)
  File "./openprompt/plms/utils.py", line 161, in padding
    ''')
ValueError: 
                    Truncated seq length '0' of 'decoder_input_ids' still greater than max length '-1.'
                    One possible reason is that no enough shortenable parts in template. Try add {"shortenable": "True"} property.

**Comment by shenxianhu** [comment]
maybe LMBFFTemplateGenerationTemplate replace all mask as text.
one example is:
[[{'text': 'nothing happens , and it happens to flat characters .', 'loss_ids': 0, 'shortenable_ids': 1}, {'text': '<extra_id_0>', 'loss_ids': 1, 'shortenable_ids': 0}, {'text': ' terrible', 'loss_ids': 0, 'shortenable_ids': 0}, {'text': '<extra_id_1>', 'loss_ids': 1, 'shortenable_ids': 0}, {'text': '.', 'loss_ids': 0, 'shortenable_ids': 0}], {'guid': 'train-0', 'label': 0}]

**Comment by cyl628** [comment]
Thanks for pointing out the bug, it seems to be an omission error of `decoder_max_length` param setting. We will fix it soon.
