### ISSUE TITLE
soft_token_num=100

### ISSUE THREAD

**Issue by BD-MF** [thunlp/OpenPrompt#90]
对于 tutorial/4.1_all_tasks_are_generation.py 中的soft_token_num=100的实验请问您进行过实验么？ 最近我在wic上的实验结果显示soft_token_num=100 的结果远低于soft_token_num=20的结果

**Comment by ningding97** [comment]
> 对于 tutorial/4.1_all_tasks_are_generation.py 中的soft_token_num=100的实验请问您进行过实验么？ 最近我在wic上的实验结果显示soft_token_num=100 的结果远低于soft_token_num=20的结果

Hi, have you conducted more experiments on other datasets? We will check the performance soon.
