### ISSUE TITLE
Does prefix-tuning support RoberTa?

### ISSUE THREAD

**Issue by TheMrYang** [thunlp/OpenPrompt#93]

**Comment by ningding97** [comment]
Prefix-tuning is proposed to solve generation problems, but the idea could surely be applied to Roberta. We need to inject continuous tokens to each Transformer layer and change the computation from auto-regressive to auto-encoding (with frozen PLM). OpenPrompt does not implement it yet, PRs are welcome!

**Comment by ShengdingHu** [comment]
Please checkout our sister repo  [OpenDelta](https://github.com/thunlp/OpenDelta) for the implementation.
