### ISSUE TITLE
Will the performance drop when using char-based models?

### ISSUE THREAD

**Issue by huhk-sysu** [thunlp/OpenPrompt#97]
The English version of BERT (`bert-base-uncased`) tokenize a sentence into subwords. Since many of them are meaningful words, the prompt learning method may act well.
However, in the Chinese version of BERT(`bert-base-chinese`) ，a sentence will be tokenized into chars (“字” in Chinese), and in Chinese individual chars are usually lack of semantics.
For example, when doing classification, in English I can use "great" as the label word, but in Chinese it become "很棒", and it's weird to ask the language model to predict "很“ from the `<mask>` in the template, in my own opinion.

In a word, I am concerned that the performance will drop for the reasons above.
Is the concern realistic? If so, how to write an appropriate Verbalizer and a Template to deal with that?

**Comment by Achazwl** [comment]
see also issue #79
